### ISSUE TITLE
graphmetadatapropertyidx cannot be automatically enabled if it is left in INSTALLED state after an error

### ISSUE THREAD

**Issue by ngrigoriev** [Newforma/janusgraph-schema-manager#5]
Schema manager fails to recover the graph schema index (internal) if it is in INSTALLED state:

5879 [main] WARN  com.newforma.titan.schema.GlobalMetaDataManager  - Graph index graphmetadatapropertyidx exists but not ENABLED, attemptint to enable
5881 [main] ERROR com.newforma.titan.schema.SchemaManagerApp  - ERROR
java.lang.IllegalArgumentException: Update action [ENABLE_INDEX] cannot be invoked for index with status [INSTALLED]
        at org.janusgraph.core.schema.SchemaAction.isApplicableStatus(SchemaAction.java:79)
        at org.janusgraph.graphdb.database.management.ManagementSystem.updateIndex(ManagementSystem.java:686)
        at com.newforma.titan.schema.GlobalMetaDataManager.ensureConfigured(GlobalMetaDataManager.java:147)
        at com.newforma.titan.schema.GlobalMetaDataManager.updateGraph(GlobalMetaDataManager.java:49)
        at com.newforma.titan.schema.SchemaManager.populateGraphMetadata(SchemaManager.java:990)
        at com.newforma.titan.schema.SchemaManager.populateNewGraphElements(SchemaManager.java:415)
        at com.newforma.titan.schema.SchemaManager.run(SchemaManager.java:173)
        at com.newforma.titan.schema.SchemaManagerApp.main(SchemaManagerApp.java:79)

**Comment by ngrigoriev** [comment]
Fixed, refactored the metadata manager code to use SchemaManager ensureIndexReady() method for the internal index.
